apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devpi-server.fullname" . }}
  labels:
    {{- include "devpi-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.data.size }}
  storageClassName: {{ .Values.data.storageClassName }}
