apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devpi-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devpi-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.auth.root.password) }}
  root-password: {{ .Values.auth.root.password | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}