apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpi-tool
  labels:
    app.kubernetes.io/name: devpi-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devpi-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devpi-tool
    spec:
      hostAliases:
        - ip: "172.17.0.1"
          hostnames:
            - "devpi-server.local"
      containers:
        - name: devpi-tool
          image: ${imageRepository}:${imageTag}
          imagePullPolicy: IfNotPresent
          env:
            - name: DEVPI_SERVER_HOST
              value: "devpi-server.local"
            - name: DEVPI_SERVER_PORT
              value: "80"
            - name: DEVPI_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: my-devpi
