apiVersion: batch/v1
kind: Job
metadata:
  name: devpi-initialize-mirror
  labels:
    app.kubernetes.io/name: devpi-initialize-mirror
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devpi-initialize-mirror
    spec:
      restartPolicy: Never
      hostAliases:
        - ip: "172.17.0.1"
          hostnames:
            - "devpi-server.local"
      containers:
        - name: devpi-initialize-mirror
          image: ${imageRepository}:${imageTag}
          imagePullPolicy: IfNotPresent
          env:
            - name: DEVPI_SERVER_SCHEMA
              value: "https"
            - name: DEVPI_SERVER_HOST
              value: "devpi-server.local"
            - name: DEVPI_SERVER_PORT
              value: "80"
            - name: DEVPI_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: my-devpi
            - name: MIRROR_URL
              value: "https://mirrors.aliyun.com/pypi/simple"
            - name: MIRROR_WEB_URL_FMT
              value: "https://mirrors.aliyun.com/pypi/simple"
            - name: INITIALIZE_INDEX_MIRROR
              value: "true"
